baseURL: https://shallowbrooksoftware.com/
title: Shallow Brook Software
theme: coder
languageCode: en-us
paginate: 20

params:
  author: Andrew Dailey
  info: Independent Programmer
  description: Simple software that babbles loudly
  footercontent: simple software that babbles loudly
  keywords: blog,developer,personal
  avatarurl: images/avatar.jpg
  social:
  - name: GitHub
    icon: fab fa-github
    url: https://github.com/theandrew168/
    weight: 1
  - name: Email
    icon: fa fa-envelope
    url: mailto:info@shallowbrooksoftware.com
    weight: 2

menu:
  main:
  - name: About
    url: /about/
    weight: 1
  - name: Projects
    url: /projects/
    weight: 2
  - name: Blog
    url: /posts/
    weight: 3

taxonomies:
  category: categories
  series: series
  tag: tags
