name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.85.0'
        extended: true
    - name: Build project
      run: |
        make dist
    - name: Copy build artifacts
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SBS_HOSTNAME }}
        username: ${{ secrets.SBS_SSH_USER }}
        key: ${{ secrets.SBS_SSH_KEY }}
        source: dist/*
        strip_components: 1
        target: /home/${{ secrets.SBS_SSH_USER }}/
    - name: Restart service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SBS_HOSTNAME }}
        username: ${{ secrets.SBS_SSH_USER }}
        key: ${{ secrets.SBS_SSH_KEY }}
        script: |
          sudo systemctl restart sbs
