name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Setup tailwindcss
      run: |
        curl -L https://github.com/tailwindlabs/tailwindcss/releases/download/v3.0.7/tailwindcss-linux-x64 -o /usr/local/bin/tailwindcss
        chmod +x /usr/local/bin/tailwindcss
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install PurgeCSS
      run: |
        npm install -g purgecss
    - name: Build blog
      run: |
        make blog
    # intentionally absent from the Makefile due to destructive behavior
    - name: Strip unused CSS
      run: >
        purgecss
        -c scripts/purgecss.config.js
        -con templates/*.tmpl
        -con posts/*.html
        -con posts/**/*.html
        -css static/css/*
        -o static/css/
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        distribution: goreleaser
        version: latest
        args: release --rm-dist --skip-validate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
