name: Test

on: [push, pull_request]

jobs:
  deploy:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Setup tailwindcss
      run: |
        curl https://github.com/tailwindlabs/tailwindcss/releases/download/v3.0.7/tailwindcss-linux-x64 -o /usr/local/bin/tailwindcss
    - name: Run tests
      run: |
        tailwindcss init
